# Generated by Django 2.1.5 on 2019-02-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='session date')),
                ('time', models.TimeField(verbose_name='end time')),
                ('tide', models.CharField(max_length=200)),
                ('conditions', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('crowd', models.CharField(max_length=200)),
                ('wind_dir', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='session date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('notes', models.CharField(max_length=200)),
                ('waves_caught', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Report')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ideal_tide', models.CharField(max_length=200)),
                ('ideal_wind', models.CharField(max_length=200)),
                ('ideal_swell_dir', models.IntegerField(default=0)),
                ('ideal_swell_height', models.IntegerField(default=0)),
                ('ideal_swell_period', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
                ('securityQuestion', models.CharField(max_length=200)),
                ('securityAnswer', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('homespot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Spot')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Spot'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Spot'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.User'),
        ),
    ]
