# Generated by Django 2.1.5 on 2019-02-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
