# Generated by Django 2.1.5 on 2019-03-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20190227_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(default='profile-photos/None/no-img.jpg', upload_to='profile-photos'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media'),
        ),
    ]
