# Generated by Django 2.1.5 on 2019-03-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20190304_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(default='profile-photos/None/no-img.jpg', upload_to='surflogs-photos'),
        ),
    ]
