# Generated by Django 2.1.5 on 2019-03-16 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_auto_20190304_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='report',
            name='time',
        ),
        migrations.RemoveField(
            model_name='wave_data',
            name='time',
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='spot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logs.Spot'),
        ),
        migrations.AlterField(
            model_name='wave_data',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='wave_data',
            name='spot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logs.Spot'),
        ),
    ]
