# Generated by Django 2.1.5 on 2019-03-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_auto_20190316_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave_data',
            name='spot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.Spot'),
        ),
    ]
