# Generated by Django 2.1.5 on 2019-03-16 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_auto_20190316_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
        migrations.AddField(
            model_name='wave_data',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='wave_data',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
