# Generated by Django 2.1.5 on 2019-03-28 22:36

from django.db import migrations, models
import surflogs.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_auto_20190326_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='surflogs-photos/None/no-img.jpg', storage=surflogs.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(default='profile-photos/None/no-img.jpg', storage=surflogs.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='wave_data',
            name='tide',
            field=models.CharField(choices=[('Low', 'Low'), ('Low Rising', 'Low Rising'), ('Mid Rising', 'Mid Rising'), ('High', 'High'), ('High Falling', 'High Falling'), ('Mid Falling', 'Mid Falling')], max_length=200),
        ),
    ]
