# Generated by Django 2.1.5 on 2019-03-31 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_auto_20190328_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('session_id', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
            ],
        ),
    ]
