# Generated by Django 2.1.5 on 2019-03-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_session_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_record',
            name='id',
        ),
        migrations.AddField(
            model_name='session_record',
            name='record_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
