# Generated by Django 2.1.5 on 2019-04-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0017_auto_20190401_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='description',
            field=models.TextField(default='No description', max_length=1000),
            preserve_default=False,
        ),
    ]
