# Generated by Django 2.1.5 on 2019-04-10 19:56

from django.db import migrations, models
import surflogs.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0018_spot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(default='profile-photos/None/no-img.jpg', storage=surflogs.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='referencing_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='ideal_swell_dir',
            field=models.CharField(max_length=200),
        ),
    ]
