# Generated by Django 2.1.5 on 2019-04-17 14:26

from django.db import migrations, models
import surflogs.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0019_auto_20190410_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(default='photos/None/no-img.jpg', storage=surflogs.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
